#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2026 by Ichiro Furusato. All rights reserved. This file is part
# of the HS Ontology Converter project, released under the MIT License.
# Please see the LICENSE file included as part of this package.
#
# author:   Ichiro Furusato
# created:  2026-03-16
# modified: 2026-03-16
#
# validate.py — Sanity checks for HS ontology YAML output files.
# 
# Validates node counts, XML Name compliance, schema completeness,
# hierarchy structure, amendment chains, and cross-file reference
# integrity across all five ontology output files.
# 
# Usage
# -----
# Validate the default current-only output (generated by convert.py):
# 
#     python validate.py
# 
# Validate a specific output directory:
# 
#     python validate.py ./ontology
# 
# Validate the full historical output (generated by convert.py --include-history):
# 
#     python validate.py ./ontology_history
# 
# Exit codes
# ----------
#     0  — all checks passed
#     1  — one or more errors found
#

import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML not found. Install with: pip install pyyaml")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Files larger than this are scanned line-by-line rather than fully parsed
LARGE_FILE_THRESHOLD_MB = 50


def load_yaml(path: Path) -> dict:
    """Load a YAML file.

    For files under LARGE_FILE_THRESHOLD_MB, parses fully with PyYAML.
    For larger files, returns a lightweight stub with node count and
    key/property sets extracted by line scanning — sufficient for all
    validation checks without loading gigabytes into RAM.
    """
    size_mb = path.stat().st_size / (1024 * 1024)
    if size_mb > LARGE_FILE_THRESHOLD_MB:
        print(f"(large file {size_mb:.0f} MB — using line scanner)", end=" ", flush=True)
        return _scan_yaml(path)
    return _parse_yaml(path)


def _parse_yaml(path: Path) -> dict:
    """Full PyYAML parse for smaller files."""
    text = path.read_text(encoding="utf-8")
    lines = [l for l in text.splitlines() if not l.startswith("#")]
    cleaned = []
    in_ontology = False
    for line in lines:
        if line.startswith("ontology:"):
            in_ontology = True
            continue
        if in_ontology:
            if line and not line.startswith(" ") and not line.startswith("\t"):
                in_ontology = False
            else:
                continue
        cleaned.append(line)
    try:
        data = yaml.safe_load("\n".join(cleaned)) or {}
    except yaml.YAMLError as e:
        print(f"  WARNING: YAML parse error in {path.name}: {e}")
        data = {}
    return data


def _scan_yaml(path: Path) -> dict:
    """Memory-efficient line scanner for large YAML files.

    Extracts node keys and their property values without building full
    nested dicts. Returns a dict of {key: {'properties': {prop: value}}}
    sufficient for all validation checks.
    """
    import re
    nodes = {}
    current_key = None
    in_properties = False
    prop_re    = re.compile(r'^        ([\w:]+):\s*(.+)$')
    key_re     = re.compile(r'^(\w[\w:.-]*):\s*$')

    display_re = re.compile(r'^    display:\s+(.+)$')

    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            # Top-level node key
            m = key_re.match(line)
            if m and not line.startswith(" "):
                current_key = m.group(1)
                if ":" in current_key:   # e.g. hs:section.s1
                    nodes[current_key] = {"display": "", "properties": {}}
                    in_properties = False
                continue
            if current_key and line.strip() == "properties:":
                in_properties = True
                continue
            if in_properties and current_key:
                m = prop_re.match(line)
                if m:
                    nodes[current_key]["properties"][m.group(1)] = m.group(2).strip()
                elif line and not line.startswith(" "):
                    in_properties = False
            elif current_key and not in_properties:
                # Capture top-level display: field
                m = display_re.match(line)
                if m:
                    val = m.group(1).strip().strip('"')
                    nodes[current_key]["display"] = val

    return nodes


def is_xml_name_compliant(key: str) -> bool:
    """Check that the local part of a namespace:key starts with a letter or underscore."""
    local = key.split(":", 1)[-1]
    # Local part after namespace — check first char after any dots
    parts = local.split(".")
    for part in parts:
        if part and part[0].isdigit():
            return False
    return True


def section(title: str) -> None:
    width = 60
    print(f"\n{'=' * width}")
    print(f"  {title}")
    print(f"{'=' * width}")


def subsection(title: str) -> None:
    print(f"\n--- {title} ---")


def ok(msg: str) -> None:
    print(f"  ✓  {msg}")


def warn(msg: str) -> None:
    print(f"  ⚠  {msg}")


def err(msg: str) -> None:
    print(f"  ✗  {msg}")


# ---------------------------------------------------------------------------
# Main validation
# ---------------------------------------------------------------------------

def validate(ontology_dir: Path) -> int:
    """Run all checks. Returns number of errors found."""
    errors = 0

    files = {
        "hs":       ontology_dir / "hs.yaml",
        "details":  ontology_dir / "tariff_details.yaml",
        "levies":   ontology_dir / "tariff_levies.yaml",
        "formulas": ontology_dir / "tariff_levy_formulas.yaml",
        "rates":    ontology_dir / "tariff_rates.yaml",
    }

    section("HS Ontology Validation")
    print(f"  Directory: {ontology_dir.resolve()}")

    # --- Check files exist ---
    subsection("File existence")
    missing = []
    for name, path in files.items():
        if path.exists():
            size = path.stat().st_size
            ok(f"{path.name:40s} {size/1024:.1f} KB")
        else:
            err(f"{path.name} not found")
            missing.append(name)
            errors += 1

    if missing:
        print(f"\n  Cannot continue — missing files: {missing}")
        return errors

    # --- Load all files ---
    subsection("Loading YAML")
    data = {}
    for name, path in files.items():
        size_mb = path.stat().st_size / (1024 * 1024)
        print(f"  Loading {path.name} ({size_mb:.0f} MB)...", end=" ", flush=True)
        data[name] = load_yaml(path)
        print(f"{len(data[name]):,} nodes")

    # --- Node counts ---
    subsection("Node counts")
    for name, nodes in data.items():
        ns_counts = defaultdict(int)
        for key in nodes:
            ns = key.split(":")[0] if ":" in key else "?"
            ns_counts[ns] += 1
        summary = ", ".join(f"{ns}: {n:,}" for ns, n in sorted(ns_counts.items()))
        print(f"  {files[name].name:40s} {len(nodes):>8,} nodes  ({summary})")

    # --- XML Name compliance ---
    subsection("XML Name compliance (no leading digits in local parts)")
    all_clean = True
    for name, nodes in data.items():
        bad = [k for k in nodes if not is_xml_name_compliant(k)]
        if bad:
            err(f"{files[name].name}: {len(bad)} non-compliant keys")
            for k in bad[:5]:
                print(f"       {k}")
            errors += len(bad)
            all_clean = False
    if all_clean:
        ok("All node keys are XML Name compliant")

    # --- Schema completeness ---
    subsection("Schema completeness (hs.yaml)")
    hs_nodes = data["hs"]
    expected_types = [
        "hs:tradedGood", "hs:section", "hs:chapter", "hs:heading",
        "hs:subheading", "hs:tariffItem", "hs:statisticalCode",
        "hs:nomenclature", "nztar:rate", "nztar:levy", "nztar:levyFormula",
    ]
    expected_relations = [
        "hs:isSectionOf", "hs:isChapterOf", "hs:isHeadingOf",
        "hs:isSubheadingOf", "hs:isTariffItemOf", "hs:isStatisticalCodeOf",
        "hs:isAmendedBy", "hs:isReplacedBy", "hs:hasAlternate",
        "nztar:hasRate", "nztar:hasLevy", "nztar:usesFormula",
        "nztar:appliesToCode",
    ]
    for term in expected_types + expected_relations:
        if term in hs_nodes:
            ok(term)
        else:
            err(f"{term} missing from hs.yaml")
            errors += 1

    # --- Hierarchy structure in tariff_details ---
    subsection("Hierarchy structure (tariff_details.yaml)")
    details = data["details"]

    level_counts = defaultdict(int)
    relation_counts = defaultdict(int)
    for key, node in details.items():
        if not isinstance(node, dict):
            continue
        # Count by level type
        props = node.get("properties", {}) or {}
        instance_of = props.get("kr:instanceOf", "")
        if instance_of:
            level_counts[instance_of] += 1
        # Count relations
        for rel in ["hs:isSectionOf", "hs:isChapterOf", "hs:isHeadingOf",
                    "hs:isSubheadingOf", "hs:isTariffItemOf",
                    "hs:isStatisticalCodeOf", "hs:isAmendedBy"]:
            if rel in props:
                relation_counts[rel] += 1

    for level, count in sorted(level_counts.items()):
        print(f"  {level:35s} {count:>8,} nodes")
    print()
    for rel, count in sorted(relation_counts.items()):
        print(f"  {rel:35s} {count:>8,} relations")

    # Sanity: sections should be ≤ 21
    section_count = level_counts.get("hs:section", 0)
    if section_count > 21:
        err(f"Too many sections: {section_count} (max 21)")
        errors += 1
    elif section_count == 0:
        err("No section nodes found")
        errors += 1
    else:
        ok(f"{section_count} sections (≤ 21)")

    # Sanity: chapters should be ≤ 97 (HS has 97 chapters)
    chapter_count = level_counts.get("hs:chapter", 0)
    if chapter_count > 99:
        err(f"Too many chapters: {chapter_count} (expected ≤ 99)")
        errors += 1
    else:
        ok(f"{chapter_count} chapters (WCO defines 97 active; 77 is reserved, 2 are NZ extensions)")

    # --- Amendment chains ---
    amended_count = relation_counts.get("hs:isAmendedBy", 0)
    subsection("Amendment chains")
    if amended_count > 0:
        ok(f"{amended_count:,} isAmendedBy links present (history mode)")
        # Check chains don't have dangling references
        all_keys = set(details.keys())
        dangling = 0
        for key, node in details.items():
            if not isinstance(node, dict):
                continue
            props = node.get("properties", {}) or {}
            target = props.get("hs:isAmendedBy")
            if target and target not in all_keys:
                dangling += 1
        if dangling:
            err(f"{dangling} dangling isAmendedBy references")
            errors += dangling
        else:
            ok("All isAmendedBy references resolve internally")
    else:
        ok("No amendment chains (current-only mode — use --include-history for full history)")

    # --- Cross-file reference integrity: rates → details ---
    subsection("Cross-file reference integrity")
    details_keys = set(details.keys())
    rates = data["rates"]
    formulas = data["formulas"]
    levies = data["levies"]

    # rates → tariff_details
    rate_refs = set()
    for key, node in rates.items():
        if not isinstance(node, dict):
            continue
        props = node.get("properties", {}) or {}
        ref = props.get("nztar:appliesToCode")
        if ref:
            rate_refs.add(ref)

    resolved   = rate_refs & details_keys
    unresolved = rate_refs - details_keys
    print(f"  tariff_rates → tariff_details:")
    print(f"    Unique appliesToCode targets: {len(rate_refs):,}")
    if unresolved:
        warn(
            f"{len(unresolved):,} rate rows reference tariff items with no active "
            f"classification in tariff_details.yaml."
        )
        print(
            f"  These are likely zombie entries in the NZ Customs source data —\n"
            f"  rates whose classification codes have been abolished but not cleaned up.\n"
            f"  They are skipped by the converter and do not affect ontology integrity."
        )
        print(f"  First 10 zombie tariff item references:")
        for ref in sorted(unresolved)[:10]:
            print(f"      {ref}")
        if len(unresolved) > 10:
            print(f"      ... and {len(unresolved) - 10} more")
        # Not counted as errors — known source data issue, handled by converter
    else:
        ok(f"All {len(resolved):,} references resolve")

    # levies → tariff_details
    levy_refs = set()
    for key, node in levies.items():
        if not isinstance(node, dict):
            continue
        props = node.get("properties", {}) or {}
        ref = props.get("nztar:appliesToCode")
        if ref:
            levy_refs.add(ref)

    levy_unresolved = levy_refs - details_keys
    print(f"  tariff_levies → tariff_details:")
    if levy_unresolved:
        warn(
            f"{len(levy_unresolved):,} levy rows reference tariff items with no "
            f"classification in tariff_details.yaml (historical or current)."
        )
        print(
            f"  These are orphaned entries in the NZ Customs source data —\n"
            f"  levies whose classification codes never existed or have been\n"
            f"  fully purged from Tariff_Details.csv. Documented in audit_report.csv."
        )
        for ref in sorted(levy_unresolved)[:10]:
            print(f"      {ref}")
        # Not counted as errors — known source data issue, documented in audit
    else:
        ok(f"All {len(levy_refs):,} levy references resolve")

    # rates/levies → levy formulas
    formula_keys = set(formulas.keys())
    formula_refs = set()
    for nodes in (rates, levies):
        for key, node in nodes.items():
            if not isinstance(node, dict):
                continue
            props = node.get("properties", {}) or {}
            ref = props.get("nztar:usesFormula")
            if ref:
                formula_refs.add(ref)

    formula_unresolved = formula_refs - formula_keys
    print(f"  rates+levies → tariff_levy_formulas:")
    if formula_unresolved:
        err(f"  {len(formula_unresolved):,} unresolved formula references")
        for ref in sorted(formula_unresolved)[:5]:
            print(f"      {ref}")
        errors += len(formula_unresolved)
    else:
        ok(f"All {len(formula_refs):,} formula references resolve")

    # --- Sample nodes ---
    subsection("Sample nodes")
    for prefix, label in [
        ("hs:section.",         "Section"),
        ("hs:chapter.",         "Chapter"),
        ("hs:statisticalCode.", "Statistical code"),
        ("nztar:rate.",         "Rate"),
    ]:
        samples = [(k, v) for k, v in details.items() if k.startswith(prefix)]
        if not samples and prefix.startswith("nztar"):
            samples = [(k, v) for k, v in rates.items() if k.startswith(prefix)]
        if samples:
            key, node = samples[0]
            display = node.get("display", "") if isinstance(node, dict) else ""
            print(f"  {label:20s} {key}  →  {display}")
        else:
            warn(f"No {label} nodes found")

    # --- Summary ---
    section("Summary")
    if errors == 0:
        ok(f"All checks passed.")
    else:
        err(f"{errors} error(s) found — review output above.")

    return errors


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    ontology_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("./ontology")
    if not ontology_dir.exists():
        print(f"Error: directory not found: {ontology_dir}")
        sys.exit(1)
    error_count = validate(ontology_dir)
    sys.exit(0 if error_count == 0 else 1)

#EOF
